/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLocalDocuments: typeof import('./../renderer/components/documents/AddLocalDocuments.vue')['default']
    AddWebDocuments: typeof import('./../renderer/components/documents/AddWebDocuments.vue')['default']
    APIKeysNotUse: typeof import('./../renderer/components/APIKeys-NotUse.vue')['default']
    AppBar: typeof import('./../renderer/components/AppBar.vue')['default']
    BackgroundWorks: typeof import('./../renderer/components/sidebar/BackgroundWorks.vue')['default']
    ChatArea: typeof import('./../renderer/components/chat/ChatArea.vue')['default']
    ChatHistory: typeof import('./../renderer/components/sidebar/ChatHistory.vue')['default']
    CreateNewChat: typeof import('./../renderer/components/sidebar/CreateNewChat.vue')['default']
    DatasetDetail: typeof import('./../renderer/components/documents/DatasetDetail.vue')['default']
    Datasets: typeof import('./../renderer/components/documents/Datasets.vue')['default']
    DataTable: typeof import('./../renderer/components/common/DataTable.vue')['default']
    Dialog: typeof import('./../renderer/components/common/Dialog.vue')['default']
    FilePreview: typeof import('./../renderer/components/common/FilePreview.vue')['default']
    FileUploader: typeof import('./../renderer/components/common/FileUploader.vue')['default']
    MarkdownViewer: typeof import('./../renderer/components/common/MarkdownViewer.vue')['default']
    MenuItems: typeof import('./../renderer/components/sidebar/MenuItems.vue')['default']
    Modal: typeof import('./../renderer/components/common/Modal.vue')['default']
    ModelSelection: typeof import('./../renderer/components/chat/ModelSelection.vue')['default']
    ModeSelection: typeof import('./../renderer/components/chat/ModeSelection.vue')['default']
    Pagination: typeof import('./../renderer/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectItem: typeof import('./../renderer/components/common/SelectItem.vue')['default']
    Settings: typeof import('./../renderer/components/sidebar/Settings.vue')['default']
    SideBar: typeof import('./../renderer/components/SideBar.vue')['default']
    SystemInformation: typeof import('./../renderer/components/sidebar/SystemInformation.vue')['default']
    Toast: typeof import('./../renderer/components/common/Toast.vue')['default']
    UserInput: typeof import('./../renderer/components/chat/UserInput.vue')['default']
  }
}
