/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLocalDocuments: typeof import('./../renderer/components/documents/AddLocalDocuments.vue')['default']
    AppBar: typeof import('./../renderer/components/AppBar.vue')['default']
    BackgroundWorks: typeof import('./../renderer/components/sidebar/BackgroundWorks.vue')['default']
    ChatHistory: typeof import('./../renderer/components/sidebar/ChatHistory.vue')['default']
    ChatIcon: typeof import('./../renderer/components/icons/ChatIcon.vue')['default']
    ChatInput: typeof import('./../renderer/components/chat/ChatInput.vue')['default']
    CheckOllamaInstall: typeof import('./../renderer/components/models/CheckOllamaInstall.vue')['default']
    ConnectionInformation: typeof import('./../renderer/components/models/ConnectionInformation.vue')['default']
    CreateNewChat: typeof import('./../renderer/components/sidebar/CreateNewChat.vue')['default']
    CreateOllamaModel: typeof import('./../renderer/components/models/CreateOllamaModel.vue')['default']
    DatasetDetail: typeof import('./../renderer/components/documents/DatasetDetail.vue')['default']
    Datasets: typeof import('./../renderer/components/documents/Datasets.vue')['default']
    DataTable: typeof import('./../renderer/components/common/DataTable.vue')['default']
    EmailIcon: typeof import('./../renderer/components/icons/EmailIcon.vue')['default']
    FilePreview: typeof import('./../renderer/components/common/FilePreview.vue')['default']
    FileUploader: typeof import('./../renderer/components/common/FileUploader.vue')['default']
    InputForm: typeof import('./../renderer/components/common/InputForm.vue')['default']
    KnowledgeIcon: typeof import('./../renderer/components/icons/KnowledgeIcon.vue')['default']
    MarkdownViewer: typeof import('./../renderer/components/common/MarkdownViewer.vue')['default']
    MenuItems: typeof import('./../renderer/components/sidebar/MenuItems.vue')['default']
    Modal: typeof import('./../renderer/components/common/Modal.vue')['default']
    ModelSelection: typeof import('./../renderer/components/chat/ModelSelection.vue')['default']
    ModeSelection: typeof import('./../renderer/components/chat/ModeSelection.vue')['default']
    Pagination: typeof import('./../renderer/components/common/Pagination.vue')['default']
    PencilIcon: typeof import('./../renderer/components/icons/PencilIcon.vue')['default']
    PresetModel: typeof import('./../renderer/components/models/PresetModel.vue')['default']
    PullOllamaModel: typeof import('./../renderer/components/models/PullOllamaModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectItem: typeof import('./../renderer/components/common/SelectItem.vue')['default']
    Settings: typeof import('./../renderer/components/sidebar/Settings.vue')['default']
    SideBar: typeof import('./../renderer/components/SideBar.vue')['default']
    SummarizationIcon: typeof import('./../renderer/components/icons/SummarizationIcon.vue')['default']
    SystemInformation: typeof import('./../renderer/components/sidebar/SystemInformation.vue')['default']
    Toast: typeof import('./../renderer/components/common/Toast.vue')['default']
    TranslationIcon: typeof import('./../renderer/components/icons/TranslationIcon.vue')['default']
    WebIcon: typeof import('./../renderer/components/icons/WebIcon.vue')['default']
  }
}
